### ISSUE TITLE
Can you share the source code of the exe program?

### ISSUE THREAD

**Issue by xichaoqiang** [sainosmichelle/TerraWare-HV#1]
Hello,I am very intresed in the HVSR inversion section. Can you share me the souce code about  foward and inversion parts of the HVSR curve?

Thank you very much.

**Comment by sainosmichelle** [comment]
Hi,
Sure, but give me a week to find the right version 😄.

**Comment by xichaoqiang** [comment]
Dear Michelle,

Thank you very much.

Here is my Email address: 

xichaoqiang@zju.edu.cn

Best regards,
Xi
